* description
  Setup basic mac development environment
* prerequisite
  Many packages are installing from source. so you need to install xcode command line tools first to compile some source code.

  just type command below and fllow the instructions.
  
  #+BEGIN_SRC bash
  $gcc
  #+END_SRC

  and then click install button.

  verify your install by

  #+BEGIN_SRC bash
  $ xcode-select -p
  /Library/Developer/CommandLineTools
  #+END_SRC
  
* install
  #+BEGIN_SRC bash
  \curl -sSL https://raw.github.com/ripple0328/mac-develop-packages/master/brewrc.sh | bash
  #+END_SRC

  the recipes is quite strainght to understand. so feel free to fork and edit
  your own package.
* what it setup
** package manager
  * brew
  * brew cask
  * launchrocket
** command tools  
  * wget
  * zsh
  * tmux
  * watch
  * the_silver_searcher
  * tmate
  * lunchy
  * homesick
  * bash-completion
  * imagemagick
** ruby
  * rvm
  * ruby (latest)
  * rubocop
  * pry,pry-doc
  * byebug
** rails
  * mysql
  * postgres
  * redis
  * qt
    used by Capybara Webkit for headless Javascript integration testing
  * rails (latest)
  * rails-composer
  * railsrc
  * [[http://pow.cx][pow]]
  * heroku-toolbelt
  * access_lint
  * csslint
** js    
  * npm
  * nodejs
  * phantomjs  
  * karma
  * requirejs
  * yo
  * bower
  * grunt
** software    
  * iterm2
  * alfred
  * skype
  * caffeine
  * dash
  * colors
  * google-chrome
  * firefox
  * textmate
  * rubymine
  * vagrant
  * whatpulse
* package manager
  using brew and brew cask as it's package manager
* depedencies
  this project is depend on:

  [[https://github.com/ripple0328/mac-install-utils][mac-install-utils]]

  
